---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalDatabase:
    enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  DB_VENDOR: h2
